services:
  postgres_db:
    container_name: postgres_db
    image: postgres:17.4-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: swiftCodes
      POSTGRES_USER: task
      POSTGRES_PASSWORD: task1234
    volumes:
      - postgres-data:/var/lib/postgresql/data

  remitly_java_app:
    container_name: remitly_java_app
    build: .
    ports:
      - 8080:8080
    environment:
        - spring.datasource.url=jdbc:postgresql://postgres_db:5432/swiftCodes
        - spring.datasource.username=task
        - spring.datasource.password=task1234
    depends_on:
      - postgres_db
volumes:
  postgres-data:
